global:
  repositoryPrefix: dajiw

catalog:
  replicaCount: 1
  image:
    name: marketplace-catalog-service
    tag: latest
    pullPolicy: Always
  service:
    port: 8080

order:
  replicaCount: 1
  image:
    name: marketplace-order-service
    tag: latest
    pullPolicy: Always
  service:
    port: 8081

ingress:
  enabled: true
  className: nginx